# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-08 15:24
from __future__ import unicode_literals

import admission.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(choices=[('AE', 'Aeronautical Engineering'), ('CSE', 'Computer Science & Engg.'), ('ECE', 'Electronics & Communication Engg.'), ('ME', 'Mechanical Engg.')], max_length=64)),
                ('second', models.CharField(blank=True, choices=[('AE', 'Aeronautical Engineering'), ('CSE', 'Computer Science & Engg.'), ('ECE', 'Electronics & Communication Engg.'), ('ME', 'Mechanical Engg.')], max_length=64, null=True)),
                ('third', models.CharField(blank=True, choices=[('AE', 'Aeronautical Engineering'), ('CSE', 'Computer Science & Engg.'), ('ECE', 'Electronics & Communication Engg.'), ('ME', 'Mechanical Engg.')], max_length=64, null=True)),
                ('fourth', models.CharField(blank=True, choices=[('AE', 'Aeronautical Engineering'), ('CSE', 'Computer Science & Engg.'), ('ECE', 'Electronics & Communication Engg.'), ('ME', 'Mechanical Engg.')], max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrationNo', models.CharField(blank=True, max_length=16, null=True)),
                ('applyYear', models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year')], max_length=16)),
                ('aadharNo', models.CharField(max_length=16)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unspecified', 'Unspecified')], max_length=16)),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64)),
                ('fatherName', models.CharField(max_length=64)),
                ('dob', models.DateField()),
                ('category', models.CharField(choices=[('Gen', 'Gen'), ('OBC', 'OBC'), ('ST', 'ST'), ('SC', 'SC')], max_length=4)),
                ('address', models.CharField(max_length=256)),
                ('course', models.CharField(choices=[('BTech', 'Bachelor of Technology'), ('MCA', 'Master of Computer Application')], max_length=16)),
                ('mobileNo', models.CharField(max_length=10)),
                ('guardianIncome', models.IntegerField()),
                ('image', models.ImageField(upload_to=admission.models.upload_location)),
                ('signImage', models.ImageField(upload_to=admission.models.upload_location)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HighSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highSchoolPassingYear', models.CharField(choices=[('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019')], max_length=16)),
                ('highSchoolBoard', models.CharField(max_length=64)),
                ('highSchoolRollNo', models.CharField(max_length=16)),
                ('highSchoolPercentageMarks', models.FloatField()),
                ('highSchoolResultImage', models.ImageField(upload_to=admission.models.upload_location)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hs', to='admission.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Intermediate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intermediatePassingYear', models.CharField(choices=[('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019')], max_length=16)),
                ('intermediateBoard', models.CharField(max_length=64)),
                ('intermediateRollNo', models.CharField(max_length=32)),
                ('intermediatePercentageMarks', models.FloatField()),
                ('intermediateResultImage', models.ImageField(upload_to=admission.models.upload_location)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inter', to='admission.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='PCM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('math', models.IntegerField()),
                ('physics', models.IntegerField()),
                ('chemistry', models.IntegerField()),
                ('intermediate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pcm', to='admission.Intermediate')),
            ],
        ),
        migrations.CreateModel(
            name='UgOrDiploma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ugOrDiplompassingYear', models.CharField(choices=[('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019')], max_length=16)),
                ('ugOrDiplomBoard', models.CharField(max_length=64)),
                ('ugOrDiplomRollNo', models.CharField(max_length=16)),
                ('ugOrDiplomBranch', models.CharField(max_length=32)),
                ('ugOrDiplomPercentageMarks', models.FloatField()),
                ('ugOrDiplomResultimage', models.ImageField(upload_to=admission.models.upload_location)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ug', to='admission.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Upsee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('catRank', models.IntegerField(blank=True, null=True)),
                ('upseeRollNo', models.CharField(blank=True, max_length=16, null=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upsee', to='admission.Candidate')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cbranch', to='admission.Candidate'),
        ),
    ]
