# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-21 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschool',
            name='highSchoolPassingYear',
            field=models.CharField(choices=[('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020')], max_length=16),
        ),
        migrations.AlterField(
            model_name='intermediate',
            name='intermediatePassingYear',
            field=models.CharField(choices=[('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020')], max_length=16),
        ),
        migrations.AlterField(
            model_name='ugordiploma',
            name='ugOrDiplompassingYear',
            field=models.CharField(choices=[('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020')], max_length=16),
        ),
    ]
