version: "3"

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  grafana_storage: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    image: fgiet_admission
    depends_on:
      - postgres
      - grafana
    volumes:
      - .:/app
    env_file:
      - ./.env/local.env
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./docker/postgresql/Dockerfile
    image: fgiet_admission_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.env/local.env

  redis:
    image: redis:5.0-alpine

  celeryworker:
    <<: *django
    image: fgiet_admission_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker
  
  prometheus:
    image: prom/prometheus
    volumes:
     - ./prometheus/:/etc/prometheus/
    ports:
     - 9090:9090

  grafana:
    image: grafana/grafana:6.5.2
    volumes:
      -   grafana_storage:/var/lib/grafana
    ports:
     - 3060:3000
    depends_on:
     - prometheus
