#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate
python /app/manage.py collectstatic --noinput
/usr/local/bin/gunicorn fgietAdmission.wsgi:application -b 0.0.0.0:8000 --chdir=/app